<?php
/**
 * Checkout Frontend — WC_GoCardless_Checkout
 *
 * Handles payment form rendering, saved mandate display, and
 * checkout-page enhancements for all GoCardless gateway variants.
 *
 * @package WC_GoCardless_Payments\Frontend
 * @since   1.0.0
 */

declare( strict_types=1 );

defined( 'ABSPATH' ) || exit;

/**
 * Class WC_GoCardless_Checkout
 *
 * @since 1.0.0
 */
class WC_GoCardless_Checkout {

	/**
	 * Constructor — register checkout-related hooks.
	 *
	 * @since 1.0.0
	 */
	public function __construct() {
		// Register WooCommerce payment token type so it can be instantiated.
		add_filter( 'woocommerce_payment_token_class', array( $this, 'register_token_class' ), 10, 2 );

		// Customise the saved token display in My Account and checkout.
		add_filter(
			'woocommerce_payment_gateway_get_saved_payment_method_option_html',
			array( $this, 'filter_saved_mandate_html' ),
			10,
			3
		);
	}

	/**
	 * Map the 'gocardless_mandate' token type to its class.
	 *
	 * @since 1.0.0
	 *
	 * @param string $class Token class name resolved so far.
	 * @param string $type  Token type identifier.
	 * @return string Resolved class name.
	 */
	public function register_token_class( string $class, string $type ): string {
		if ( 'gocardless_mandate' === $type ) {
			return 'WC_GoCardless_Payment_Token_Mandate';
		}

		return $class;
	}

	/**
	 * Customise the HTML for saved GoCardless mandate options in the checkout.
	 *
	 * Replaces the default WooCommerce token HTML with a mandate-specific label
	 * that shows the bank name, account ending, and scheme.
	 *
	 * @since 1.0.0
	 *
	 * @param string             $html    Default token HTML generated by WooCommerce.
	 * @param WC_Payment_Token   $token   Payment token object.
	 * @param WC_Payment_Gateway $gateway Gateway the token belongs to.
	 * @return string Modified HTML.
	 */
	public function filter_saved_mandate_html(
		string $html,
		WC_Payment_Token $token,
		WC_Payment_Gateway $gateway
	): string {
		if ( ! $token instanceof WC_GoCardless_Payment_Token_Mandate ) {
			return $html;
		}

		$label = sprintf(
			'<span class="wc-gocardless-saved-mandate">%s</span>',
			esc_html( $token->get_display_name() )
		);

		if ( ! $token->is_active() ) {
			$label .= sprintf(
				' <span class="wc-gocardless-mandate-status wc-gocardless-mandate-inactive">%s</span>',
				esc_html__( '(Inactive)', 'wc-gocardless-payments' )
			);
		}

		return str_replace( $token->get_display_name(), $label, $html );
	}

	/**
	 * Render the payment method description for a GoCardless gateway.
	 *
	 * Outputs the gateway description and a sandbox notice when in test mode.
	 *
	 * @since 1.0.0
	 *
	 * @param WC_GoCardless_Gateway $gateway The GoCardless gateway instance.
	 * @return void
	 */
	public static function render_payment_fields( WC_GoCardless_Gateway $gateway ): void {
		$description = $gateway->get_description();

		if ( $gateway->is_sandbox() ) {
			$description .= ' <span class="wc-gocardless-sandbox-badge">' .
				esc_html__( 'Test Mode', 'wc-gocardless-payments' ) .
				'</span>';
		}

		if ( $description ) {
			echo '<div class="wc-gocardless-payment-box">';
			echo wp_kses_post( wpautop( wptexturize( $description ) ) );
			echo '</div>';
		}

		echo '<p class="wc-gocardless-redirect-notice">';
		echo esc_html__(
			'You will be securely redirected to authorise your payment via GoCardless.',
			'wc-gocardless-payments'
		);
		echo '</p>';
	}
}
